### ISSUE TITLE
[BUG]: Knex: Timeout acquiring a connection

### ISSUE THREAD

**Issue by SVronskiy** [Fekide/strapi-plugin-translate#154]
**Describe the bug**
After starting translation with LibreTranslate plugin  I'm continiously getting error:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/srv/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Runner.ensureConnection (/srv/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/srv/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/srv/app/node_modules/@strapi/database/lib/query/query-builder.js:481:22)
    at async Object.count (/srv/app/node_modules/@strapi/database/lib/entity-manager/index.js:199:19)
```

**To Reproduce**
1. Go to '/admin/plugins/translate'
2. Click on 'Translate' in the row 'Company' and column 'ru' 

**Expected behavior**
Translation should be done of all set of untranslated records without errors.

**System:**
 - OS: macos
 - Browser firefox
 - Versions:
   - strapi: 4.7.1
   - strapi-plugin-translate: 1.1.1
   - provider: strapi-provider-translate-libretranslate@1.0.0
   - Other Strapi plugins:
  - strapi-provider-rest-cache-memory@4.2.6

**Plugin.js config**
```
  // ...
  translate: {
    enabled: true,
    config: {
      // Choose one of the available providers
      provider: 'libretranslate',
      // Pass credentials and other options to the provider
      providerOptions: {
        // your API key - required and wil cause errors if not provided
        apiKey: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        // api url - required 
        apiUrl: 'https://translate.somesite.com/',
        // maximum number of requests per minute - optional, default is `undefined` => no limit
        apiMaxRPM: 40,
        // maximum number of chars per request - optional, default is `undefined` => no limit
        apiMaxChars: 1234,
        // maximum number of texts per request
        apiMaxTexts: 55,
        // manually overwrite the Strapi Locale to LibreTranslate Locale mapping.
        // default is the string before the `-` character for every locale
        localeMap:{ }
      },
      // other options ...
    },
  },
  // ...
```
Database.js config:
```
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', 'IP'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'database'),
      user: env('DATABASE_USERNAME', 'postgres'),
      password: env('DATABASE_PASSWORD', 'SomePassword'),
//      ssl: env.bool('DATABASE_SSL', false),
      ssl: {
        rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
      },
    },
    // https://github.com/strapi/strapi/issues/11860
    debug: false,
    acquireConnectionTimeout: 600000,
    pool: {
      min: 0,
      max: 40,
      acquireTimeoutMillis: 300000,
      createTimeoutMillis: 300000,
      destroyTimeoutMillis: 50000,
      idleTimeoutMillis: 300000,
      reapIntervalMillis: 10000,
      createRetryIntervalMillis: 2000,
      propagateCreateError: false,
    },  
  },
});

```

**Comment by SVronskiy** [comment]
Removing packages strapi-plugin-rest-cache and strapi-provider-rest-cache-memory doen't help.

**Comment by layaxx** [comment]
Hi @SVronskiy,
I'm trying to reproduce this at the moment.
I noticed the `apiMaxChars: 1234` in your config. I know this is the value from the providers README, but that was just supposed to be an example of a random number. Unless your LibreTranslate server really does have a limit of 1234 characters per request, can you try increasing this value or omitting it if your server does not have a limit?

Also, could you possibly share more information about the texts you are trying to batch translate, i.e. how many entities, how many fields per entity, how many characters per field (on average)? I am currently having trouble reproducing/pinpointing the issue.

**Comment by SVronskiy** [comment]
Hello, @layaxx !
It happens on tables with 30M+ of records with 10+ languages. Slow queries are reason of errors. I think query optimization will resolve the issue. I'm closing it for a moment.
