### ISSUE TITLE
Provider LibreTranslate

### ISSUE THREAD

**Issue by SVronskiy** [Fekide/strapi-plugin-translate#87]
Hello! 

Can you please implement strapi translate provider for [libretranslate](https://libretranslate.com/)?

**Comment by layaxx** [comment]
I will look into it, but you can expect it to take a few weeks/months, as I don't have a lot of free time at the moment

**Comment by SVronskiy** [comment]
Hello!

LibreTranslate batch tranlsation continiously completed with errors:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/Users/a123/repos/project/backend/src/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
    at async Runner.ensureConnection (/Users/a123/repos/project/backend/src/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/Users/a123/repos/project/backend/src/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/Users/a123/repos/project/backend/src/node_modules/@strapi/database/lib/query/query-builder.js:481:22)
    at async Object.count (/Users/a123/repos/project/backend/src/node_modules/@strapi/database/lib/entity-manager/index.js:199:19)
```

Updating config/database.js as described at https://github.com/strapi/strapi/issues/11860 doesn't help me.

**Comment by sargreal** [comment]
@SVronskiy can you please open a new issue for this with the bug template filled out?
